# Generated by Django 3.1.3 on 2020-11-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marka', models.CharField(max_length=75)),
                ('Model', models.CharField(max_length=75)),
                ('Rok_produkcji', models.DateField()),
                ('numer_rejestracyjny', models.CharField(max_length=75)),
                ('moc_silnika', models.CharField(max_length=15, null=True)),
                ('pojemnosc_silnika', models.CharField(max_length=15)),
                ('zdjecie', models.TextField()),
                ('przebieg', models.FloatField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Cennik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cena_za_dobe', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imie', models.CharField(max_length=75)),
                ('Nazwisko', models.CharField(max_length=75)),
                ('PESEL', models.FloatField(max_length=10)),
                ('numer_dowodu_osobistego', models.FloatField(max_length=8)),
                ('Miejscowosc', models.CharField(max_length=75)),
                ('Ulica', models.CharField(max_length=75, null=True)),
                ('Numer_domu', models.FloatField(max_length=3, null=True)),
                ('Numer_mieszkania', models.FloatField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wypozyczenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozyczenia', models.DateField()),
                ('termin_zwrotu_zwrotu', models.DateField()),
                ('auto_id_auta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firma_zlomek.auto')),
                ('cennik_id_cennika', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firma_zlomek.cennik')),
                ('klient_id_klienta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firma_zlomek.klient')),
            ],
        ),
        migrations.CreateModel(
            name='Zwroty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stan_licznika_po', models.FloatField(max_length=3)),
                ('data_zwrotu', models.DateField()),
                ('wypozyczenia_id_wypozyczenia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firma_zlomek.wypozyczenia')),
            ],
        ),
        migrations.CreateModel(
            name='Ubezpieczenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_konca_ubezpieczenia', models.DateField()),
                ('Data_poczatku_ubezpieczenia', models.DateField()),
                ('numer_ubezpieczenia', models.FloatField(max_length=20)),
                ('Ubezpieczyciel', models.CharField(max_length=75)),
                ('cena_ubezpieczenia', models.FloatField(max_length=5)),
                ('auto_id_auta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firma_zlomek.auto')),
            ],
        ),
        migrations.CreateModel(
            name='Przeglad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_konca_przegladu', models.DateField()),
                ('Data_poczatku_przegladu', models.DateField()),
                ('auto_id_auta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firma_zlomek.auto')),
            ],
        ),
    ]
