# Generated by Django 3.1.3 on 2020-11-25 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firma_zlomek', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='pojemnosc_silnika',
        ),
    ]
