# Generated by Django 3.1.3 on 2020-12-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma_zlomek', '0002_remove_auto_pojemnosc_silnika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='zdjecie',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='klient',
            name='PESEL',
            field=models.FloatField(max_length=11),
        ),
    ]
