# Generated by Django 3.1.3 on 2020-12-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firma_zlomek', '0004_auto_20201206_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='zdjecie',
        ),
    ]
