# Generated by Django 3.1.3 on 2021-01-27 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firma_zlomek', '0009_auto_20201207_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auto',
            options={'ordering': ('Marka',)},
        ),
        migrations.AlterModelOptions(
            name='klient',
            options={'ordering': ('Imie',)},
        ),
        migrations.AlterModelOptions(
            name='przeglad',
            options={'ordering': ('Data_konca_przegladu',)},
        ),
        migrations.AlterModelOptions(
            name='ubezpieczenie',
            options={'ordering': ('auto_id_auta',)},
        ),
        migrations.AlterModelOptions(
            name='wypozyczenia',
            options={'ordering': ('klient_id_klienta',)},
        ),
        migrations.AlterModelOptions(
            name='zwroty',
            options={'ordering': ('data_zwrotu',)},
        ),
        migrations.AddField(
            model_name='auto',
            name='wlasciciel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wlasciciele', to='auth.user'),
            preserve_default=False,
        ),
    ]
