# Generated by Django 3.1.3 on 2021-02-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firma_zlomek', '0011_auto_20210131_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='Marka',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='numer_rejestracyjny',
            field=models.CharField(max_length=75),
        ),
    ]
